<a href="https://colab.research.google.com/github/Muluken1Walle/NumpyPandasAssignment/blob/main/Numpy_Pandas_Assingment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd


In [21]:
print(np.zeros((3,3)))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.zeros((4,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
a= np.random.randint(2,10,(3,4))
b= np.random.randint(2,10,(4,3))

In [22]:
a.dot(b)

array([[ 72,  96,  96],
       [146, 201, 198],
       [ 86, 119, 114]])

In [23]:
import pandas as pd
data= pd.read_csv('/content/data.csv')


In [25]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  
0   0.135641  
1   0.080067  
2   0.119868  
3   0.128733  
4   0.125546

In [36]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB


In [37]:
data.shape

(25, 6)

In [27]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

In [29]:
data.isnull().sum()

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64

In [31]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

In [32]:
GroupTable=data.groupby('DESCRIPTION').mean()
GroupTable

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

In [33]:
Sample=data.sample(n=10)

In [35]:
Sample

OBJECTID                                   UNIT_NAME  \
14        33                     Turtle River State Park   
19        40  Head of the Mountain State Nature Preserve   
8         29         Lewis and Clark Interpretive Center   
10        31                  Little Missouri State Park   
11        32                      Sully Creek State Park   
16        37                  Elkhorn State Natural Area   
4         25                   Grahams Island State Park   
12        35        Butte St. Paul State Recreation Area   
17        38         Fahlgren Park State Recreation Area   
5         26                        Icelandic State Park   

              DESCRIPTION    ACRES  SHAPE.AREA  SHAPE.LEN  
14             State Park   775.28    0.000378   0.145220  
19  State Nature Preserve    72.30    0.000034   0.033885  
8     Interpretive Center    14.71    0.000007   0.016774  
10             State Park  6492.93    0.003136   0.313756  
11             State Park    63.03    0.000030   0.024016  
16     State Natural Area   264.84    0.000127   0.067082  
4              State Park   959.33    0.000469   0.125546  
12  State Recreation Area    51.23    0.000025   0.022095  
17  State Recreation Area    21.56    0.000010   0.013294  
5              State Park   930.30    0.000461   0.166712

In [38]:
data['New_feature']=np.random.rand(25)

In [39]:
data.head()

OBJECTID                        UNIT_NAME DESCRIPTION   ACRES  SHAPE.AREA  \
0        21        Fort Stevenson State Park  State Park  586.48    0.000284   
1        22           Beaver Lake State Park  State Park  273.16    0.000129   
2        23  Fort Abraham Lincoln State Park  State Park  836.47    0.000399   
3        24           Fort Ransom State Park  State Park  933.78    0.000444   
4        25        Grahams Island State Park  State Park  959.33    0.000469   

   SHAPE.LEN  New_feature  
0   0.135641     0.808746  
1   0.080067     0.032249  
2   0.119868     0.664552  
3   0.128733     0.949290  
4   0.125546     0.051274

In [40]:
data['OBJECTID']=data['OBJECTID'].replace(0,data['OBJECTID'].mean())
data['OBJECTID']

0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64